-- SQL para crear la tabla de mantenimientos en Oracle 21c
-- Ejecutar en SQL Developer para resolver el error 500 (Table not found)

CREATE TABLE AGRO_MANTENIMIENTO (
    MAN_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SECC_SECCION NUMBER NOT NULL,
    MAN_TIPO VARCHAR2(100) NOT NULL,
    MAN_FRECUENCIA_DIAS NUMBER NOT NULL,
    MAN_ULTIMA_FECHA TIMESTAMP,
    MAN_PROXIMA_FECHA TIMESTAMP,
    CONSTRAINT FK_MANT_SECCION FOREIGN KEY (SECC_SECCION) REFERENCES AGRO_SECCION(SECC_SECCION)
);
