import { AppDataSource } from "../config/data-source";

const setupTable = async () => {
    try {
        await AppDataSource.initialize();
        console.log("Data Source has been initialized!");

        const result = await AppDataSource.query(`
            SELECT table_name FROM user_tables WHERE table_name = 'AGRO_REPORTES'
        `);

        if (result.length === 0) {
            console.log("Creando tabla AGRO_REPORTES...");
            await AppDataSource.query(`
                CREATE TABLE AGRO_REPORTES (
                    REPO_REPORTE NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    REPO_FECHA TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                    REPO_TIPO VARCHAR2(100) NOT NULL,
                    REPO_SECCIONES VARCHAR2(255) NOT NULL,
                    REPO_PDF_PATH VARCHAR2(500) NOT NULL,
                    FIN_FINCA NUMBER NOT NULL,
                    USU_USUARIO NUMBER,
                    REPO_USUARIO_NOMBRE VARCHAR2(150)
                )
            `);
            console.log("Tabla AGRO_REPORTES creada correctamente.");
        } else {
            console.log("La tabla AGRO_REPORTES ya existe.");
        }

        process.exit(0);
    } catch (error) {
        console.error("Error during Data Source initialization", error);
        process.exit(1);
    }
};

setupTable();
